### PR TITLE
Allow partials to be looked up relative to app view

### LINKED ISSUE #12: Feature request: partial paths to also look at relative path from app.set('views')
Would you be interested in having partial paths also look at paths relative to the app.set('views') if the partial isn't found relative to the file first? This would allow two nice features:

1. Deeply nested view directories can access partials without having to put in back directories.
2. With app.set('views') now being an array, accessing partials in a separate view path is also easier.

If you like the idea, I can write up a pull request with it along with the appropriate tests.

### PR DESCRIPTION
**Pull request by lambertsteven**
Allows partials to be looked up relative to the app view if it isn't found relative to the file.

Closes #12.

### CODE REVIEW

**Comment by JacksonTian** [comment]
LGTM. would you like to do a rebase. combine these useless commits.

**Comment by lambertsteven** [comment]
I'm not sure why it want's to added my previous pull commits to this one, but I rebased back to your last commit and my sync.

**Comment by JacksonTian** [comment]
landed in b5d7ce4fa54a6ca3c68 .

**Comment by JacksonTian** [comment]
Thanks.

**Comment by lambertsteven** [comment]
Awesome, thanks.

**Pull request closed without merging**
